### ISSUE TITLE
Wrong name of downloaded .deb

### ISSUE THREAD

**Issue by VNovotna** [hroncok/meshmixer-docker#2]
Makefile seems to expect _meshmixer_2.9_amd64.deb_ while the downloaded file is named _original_meshmixer_2.9_amd64.deb_.
Simple cp has fixed it.

**Comment by hroncok** [comment]
The wget in Makefile should download the file as `original_meshmixer_2.9_amd64.deb`, doesn't it?

See `-O` option here https://github.com/hroncok/meshmixer-docker/blob/master/Dockerfile#L13

**Comment by VNovotna** [comment]
This is the output on freshly cloned repo:

```
meshmixer-docker$ make
wget https://s3.amazonaws.com/autodesk-meshmixer/meshmixer/amd64/meshmixer_2.9_amd64.deb -O original_meshmixer_2.9_amd64.deb
--2016-01-02 23:50:01--  https://s3.amazonaws.com/autodesk-meshmixer/meshmixer/amd64/meshmixer_2.9_amd64.deb
Překládám s3.amazonaws.com (s3.amazonaws.com)… 54.231.9.80
Navazuje se spojení s s3.amazonaws.com (s3.amazonaws.com)|54.231.9.80|:443… spojeno.
HTTP požadavek odeslán, program čeká na odpověď… 200 OK
Délka: 36583156 (35M) [application/octet-stream]
Ukládám do: „original_meshmixer_2.9_amd64.deb“

original_meshmixer_2.9_amd64.deb                   100%[==================================================================================================================>]  34,89M  1,07MB/s   za 35s    

2016-01-02 23:50:36 (1,00 MB/s) – „original_meshmixer_2.9_amd64.deb“ uloženo [36583156/36583156]

rm -rf deb 2> /dev/null || :
mkdir -p deb/DEBIAN
dpkg -e original_meshmixer_2.9_amd64.deb deb/DEBIAN/
dpkg -x original_meshmixer_2.9_amd64.deb deb/
head deb/DEBIAN/postinst -n`grep ldconfig deb/DEBIAN/postinst -n | tail -n 1 | cut -d: -f1` > deb/DEBIAN/postinstnew
mv deb/DEBIAN/postinst{new,}
mv: za „deb/DEBIAN/postinst{new,}“ chybí název cílového souboru
Více informací získáte příkazem „mv --help“.
Makefile:10: návod pro cíl „meshmixer_2.9_amd64.deb“ selhal
make: *** [meshmixer_2.9_amd64.deb] Chyba 1
meshmixer-docker$
```

I just discovered that renaming original_meshmixer_2.9_amd64.deb to meshmixer_2.9_amd64.deb fixed the problem.

**Comment by hroncok** [comment]
OK, renaming it to `meshmixer_2.9_amd64.deb` is not fixing the problem, there is a procedure that takes original deb downloaded from the website and makes some little adjustment.

The adjustment here does not work because the following command failed:

```
mv deb/DEBIAN/postinst{new,}
```

Which could be fixed by replacing the command with:

```
mv deb/DEBIAN/postinstnew deb/DEBIAN/postinst
```

But is quite weird that it doesn't work. What is your Shell? Could you do the following?

```
touch tmp_fileAAA
mv tmp_file{AAA,}
```

And let me know of the result?

**Comment by VNovotna** [comment]
Oh I see.

```
:) meshmixer-docker$ touch tmp_fileAAA
:) meshmixer-docker$ mv tmp_file{AAA,}
:) meshmixer-docker$ bash --version
GNU bash, verze 4.3.42(1)-release (x86_64-pc-linux-gnu)
Copyright © 2013 Free Software Foundation, Inc.
Licence GPLv3+: GNU GPL verze 3 nebo novější <http://gnu.org/licenses/gpl.html>

Toto je svobodné programové vybavení: máte právo jej měnit a šířit.
VEŠKERÉ ZÁRUKY chybí, jak jen zákon dovoluje.
:) meshmixer-docker$ 
```

(smile is indicating zero return code)
The box is Ubuntu 15.10 .

EDIT: Could it be that `make` use some different shell?

**Comment by hroncok** [comment]
That's weird. Nevertheless, if you change the line according to my previous comment, does it help? You'll have to delete `meshmixer_2.9_amd64.deb` to test it.

**Comment by VNovotna** [comment]
`mv deb/DEBIAN/postinstnew deb/DEBIAN/postinst`
fixed the issue

**Comment by hroncok** [comment]
Isn't it possible, that #3 was related to that?

**Comment by VNovotna** [comment]
It is related. I didn’t really looked on that "little adjustment" to the package. Now it's building images without any modification to Dockerfile.
Please consider issue #3 as a false alarm.
