### ISSUE TITLE
anyone happen to have the 2.9 deb file hanging around

### ISSUE THREAD

**Issue by dlarue** [hroncok/meshmixer-docker#4]
the deb package is no longer at the link in the script... curses AutoDesk!

**Comment by hroncok** [comment]
2.7 is linked from https://github.com/AppImage/pkg2appimage/blob/master/recipes/Meshmixer.yml

2.9 is probably unfortunately lost forever

**Comment by dlarue** [comment]
I found 2.9!  It was in a Ubuntu Xenial repository. 
http://openartist.org/debian/xenial64/

**Comment by dlarue** [comment]
BTW, I now have MeshMixer working in an NVidia optimized docker container.  Has taken me something like 3 hours but it's working.
